# Theme settings
doks:
    domain: lizj28.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
    url: https://lizj28.github.io  # the base hostname and protocol for your site, e.g. http://example.com
    baseurl: /recommendation_engine      # place folder name if the site is served in a subfolder
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: '#LizzyPy'
            image: true
    footer:
        content:
            logo:
                text: Liz Johnson
                image:
            copyright: Made with ♥ in Dallas by Liz &copy; 2023<br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/LizJohn58223559'
            - network_name: github
              profile_url: 'https://github.com/lizj28'
            - network_name: medium
              profile_url: 'https://medium.com/@lizjohnson_83228'
            - network_name: linkedin
              profile_url: 'https://www.linkedin.com/in/liz-johnson-88610b67'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
