# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: '#LizzyPy'
            image: true
    footer:
        content:
            logo:
                text: Liz Johnson
                image:
            copyright: Made with <img class="site-footer__heart" src="/doks-theme/assets/images/production_assets/heart_emoji.svg"> in Dallas by Liz &copy; 2023<br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/LizJohn58223559'
            - network_name: github
              profile_url: 'https://github.com/lizj28'
            - network_name: medium
              profile_url: 'https://medium.com/@lizjohnson_83228'
            - network_name: linkedin
              profile_url: 'https://www.linkedin.com/in/liz-johnson-88610b67'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
